name: Build Docker Image

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: "Checkout repository"

      - name: "Prepare Docker buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Authenticate with GHCR"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN}}

      - name: "Build and Push"
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: "master"
          cache-from: type=gha
          cache-to: type=gha,mode=max
